FROM python:3.8-slim
COPY requirements.txt /requirements.txt
RUN python -m pip install --upgrade pip && pip install -r /requirements.txt

COPY utils utils
COPY run-flask.sh ./
ENV FLASK_APP runner.py

ARG NAME
ENV SOURCE ${NAME}

COPY ${SOURCE} ${SOURCE}

RUN cp ${SOURCE}/config.py ./ && cp ${SOURCE}/runner.py ./ \
    && chmod +x run-flask.sh \
    && cp -R ${SOURCE}/migrations migrations

ENTRYPOINT ["./run-flask.sh"]
