"""add batch status table

Revision ID: 32a1380fdbfc
Revises: 
Create Date: 2020-04-23 12:46:00.274872

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '32a1380fdbfc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch',
    sa.Column('batch_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('file_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=True),
    sa.Column('loaded', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('batch_id', 'file_id')
    )
    op.create_index(op.f('ix_batch_batch_id'), 'batch', ['batch_id'], unique=False)
    op.create_index(op.f('ix_batch_file_id'), 'batch', ['file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batch_file_id'), table_name='batch')
    op.drop_index(op.f('ix_batch_batch_id'), table_name='batch')
    op.drop_table('batch')
    # ### end Alembic commands ###
