"""add rating table

Revision ID: 3304acd0f0d1
Revises: a773e335a121
Create Date: 2020-04-16 18:48:18.940385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3304acd0f0d1"
down_revision = "a773e335a121"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rating",
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["game_id"], ["game.id"],),
        sa.PrimaryKeyConstraint("game_id", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rating")
    # ### end Alembic commands ###
