"""add players count

Revision ID: a773e335a121
Revises: f95314d1f11c
Create Date: 2020-04-16 14:06:45.532450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a773e335a121"
down_revision = "f95314d1f11c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("game", sa.Column("max_players", sa.Integer(), nullable=True))
    op.add_column("game", sa.Column("min_players", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game", "min_players")
    op.drop_column("game", "max_players")
    # ### end Alembic commands ###
