"""add games table

Revision ID: f95314d1f11c
Revises: 
Create Date: 2020-04-15 18:45:14.174897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f95314d1f11c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("category", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_game_category"), "game", ["category"], unique=False)
    op.create_index(op.f("ix_game_name"), "game", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_game_name"), table_name="game")
    op.drop_index(op.f("ix_game_category"), table_name="game")
    op.drop_table("game")
    # ### end Alembic commands ###
